### ISSUE TITLE
feature: Workspace data dir should be unique

### ISSUE THREAD

**Issue by jvalkeal** [nvim-java/nvim-java-core#54]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Currently `jdtls` is launched with something like `-data /home/jvalkealahti/.cache/nvim/jdtls/workspaces/common-workspace`. All the examples around `jdtls` seems to propose to just use a common directory which imho is just wrong. When you re-launch `jdtls` or used a completely different project, `jdtls` will actually partially wipe stuff from its _data_ directory.

That's why i.e. vscode will calculate a hash(based on your project root) and uses that to launch `jdtls` with unique _data_ directory.

### Describe the solution you'd like

In my `nvim-jdtls` setup i've just been using this relatively naive hack which with this plugin would look something like:
```
local project_name = string.gsub(vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h"), "/", "_")
local path = join(cache_dir, 'nvim', 'jdtls', 'workspaces', 'common-workspace', project_name)
```

That would give you something like `/home/jvalkealahti/.cache/nvim/jdtls/workspaces/common-workspace/_home_jvalkealahti_path_to_projectroot`.

Lua don't have any buildin hash functions so we'd just need to come up with something else which creates a unique directory name.

### Describe alternatives you've considered

Don't there's any.

**Comment by s1n7ax** [comment]
@jvalkeal Good point. I will add this to next release.

**Comment by jvalkeal** [comment]
I could work on these issues I'm creating.

**Comment by s1n7ax** [comment]
Might help. Small enough to include in utils

https://gist.github.com/liukun/f9ce7d6d14fa45fe9b924a3eed5c3d99
